import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs'
import { resolve, join } from 'node:path'
import {
  generateRobotsTxt,
  generateLlmsTxt,
  generateLlmsFullTxt,
  generateAgentsTxt,
  generateAgentsJson,
  generateSitemapXml,
  parseSitemap,
  crawlWithFirecrawl,
  validateRobotsTxt,
  validateLlmsTxt,
  validateAgentsTxt,
  validateAgentsJson,
  validateSitemapXml,
  ROBOTS_GENERATED_MARKER,
  type AgenticConfig,
  type PageEntry,
} from '@agentify/core'
import { AgenticConfigSchema } from '../config-schema.js'

interface GenerateOptions {
  config: string
  out: string
  skipRobots?: boolean
  skipLlms?: boolean
  skipAgents?: boolean
  sitemap?: boolean
  skipSitemap?: boolean
}

async function loadConfig(configPath: string): Promise<AgenticConfig> {
  const abs = resolve(configPath)
  if (!existsSync(abs)) {
    throw new Error(
      `Config not found at ${abs}.\nRun \`agentify init\` to create one.`,
    )
  }

  try {
    const mod = await import(abs) as { default?: unknown } | unknown
    const raw = (typeof mod === 'object' && mod !== null && 'default' in mod)
      ? (mod as { default: unknown }).default
      : mod

    const result = AgenticConfigSchema.safeParse(raw)
    if (!result.success) {
      const issues = result.error.issues
        .map((i) => `  • ${i.path.join('.') || '(root)'}: ${i.message}`)
        .join('\n')
      throw new Error(`Invalid agentic.config.js:\n${issues}`)
    }

    return result.data as AgenticConfig
  } catch (err) {
    throw new Error(`Failed to load config: ${String(err)}`)
  }
}

export async function generateCommand(options: GenerateOptions): Promise<void> {
  console.log('\n🤖 agentify — generating files...\n')

  let config: AgenticConfig
  try {
    config = await loadConfig(options.config)
  } catch (err) {
    console.error(`❌ ${String(err)}`)
    process.exit(1)
  }

  const outDir = resolve(options.out)
  mkdirSync(outDir, { recursive: true })

  // ── robots.txt ────────────────────────────────────────────────────────────
  if (!options.skipRobots) {
    const robotsPath = join(outDir, 'robots.txt')
    let existingRobots: string | undefined
    if (existsSync(robotsPath)) {
      const raw = readFileSync(robotsPath, 'utf-8')
      // If the file was previously generated by this tool, only preserve the
      // human-authored section that was appended below the "Existing rules" marker.
      // Without this, re-running generate would duplicate the entire generated block.
      // ROBOTS_GENERATED_MARKER is exported from @agentify/core so the marker
      // string lives next to the code that emits it — single source of truth.
      const EXISTING_RULES_MARKER = '# ── Existing rules (preserved) ──────────────────────────────'
      if (raw.includes(ROBOTS_GENERATED_MARKER)) {
        const markerIdx = raw.indexOf(EXISTING_RULES_MARKER)
        if (markerIdx !== -1) {
          const tail = raw.slice(markerIdx + EXISTING_RULES_MARKER.length).trim()
          existingRobots = tail || undefined
        }
        // else: pure generated file with no user section — just overwrite cleanly
      } else {
        existingRobots = raw
        console.log(`   ⚡ Merging with existing robots.txt`)
      }
    }
    const robotsTxt = generateRobotsTxt(config, existingRobots)
    writeFileSync(robotsPath, robotsTxt, 'utf-8')
    console.log(`   ✔  robots.txt → ${robotsPath}`)
    for (const r of validateRobotsTxt(robotsTxt, config).filter((v) => v.status !== 'pass')) {
      console.warn(`      ⚠  ${r.message}`)
    }
  } else {
    console.log(`   ⏭  robots.txt skipped`)
  }

  // ── llms.txt ──────────────────────────────────────────────────────────────
  if (!options.skipLlms) {
    try {
      const llmsTxt = await generateLlmsTxt(config)
      const llmsPath = join(outDir, 'llms.txt')
      writeFileSync(llmsPath, llmsTxt, 'utf-8')
      console.log(`   ✔  llms.txt  → ${llmsPath}`)
      for (const r of validateLlmsTxt(llmsTxt).filter((v) => v.status !== 'pass')) {
        console.warn(`      ⚠  ${r.message}`)
      }

      if (config.content?.fullTxt) {
        const llmsFullTxt = await generateLlmsFullTxt(config)
        const llmsFullPath = join(outDir, 'llms-full.txt')
        writeFileSync(llmsFullPath, llmsFullTxt, 'utf-8')
        const sourceType = config.content.fullTxt.driver.type
        const note = sourceType === 'firecrawl' ? '(content scraped via Firecrawl)' : `(${sourceType} source — link-list only)`
        console.log(`   ✔  llms-full.txt → ${llmsFullPath}  ${note}`)
      }
    } catch (err) {
      console.warn(`   ⚠  llms.txt generation failed: ${String(err)}`)
      console.warn(`      Add content.driver config or use --skip-llms`)
    }
  }

  // ── sitemap.xml ───────────────────────────────────────────────────────────
  // Default policy: emit when content.driver is 'static' or 'manual' (user-supplied
  // authoritative URL list). Skip 'sitemap' (circular — we'd be reading our own
  // output) and 'firecrawl' (curated subset, not authoritative). Both opt-in/out
  // overrides honor --sitemap and --skip-sitemap.
  if (!options.skipSitemap) {
    const driver = config.content?.driver
    const driverType = driver?.type
    const defaultEmit = driverType === 'static' || driverType === 'manual'
    const shouldEmit = options.sitemap || defaultEmit

    if (shouldEmit) {
      if (driverType === 'sitemap' && options.sitemap) {
        console.warn(`   ⚠  --sitemap with driver 'sitemap' is circular (reading the file we'd overwrite). Skipping.`)
      } else {
        try {
          let pages: PageEntry[] = []
          if (driver?.type === 'static') {
            pages = [
              ...driver.pages,
              ...(driver.sections ?? []).flatMap((s) => s.pages),
            ]
          } else if (driver?.type === 'manual') {
            pages = driver.sections.flatMap((s) => s.pages)
          } else if (driver?.type === 'firecrawl') {
            pages = await crawlWithFirecrawl(driver)
          } else if (driver?.type === 'sitemap') {
            // unreachable here (handled above), but keep exhaustive
            pages = await parseSitemap(driver.sitemapUrl)
          }

          if (pages.length === 0) {
            console.warn(`   ⚠  sitemap.xml: no pages resolved from content driver — skipping`)
          } else {
            const sitemapXml = generateSitemapXml(pages)
            const sitemapPath = join(outDir, 'sitemap.xml')
            writeFileSync(sitemapPath, sitemapXml, 'utf-8')
            console.log(`   ✔  sitemap.xml → ${sitemapPath}  (${pages.length} URLs)`)
            for (const r of validateSitemapXml(sitemapXml).filter((v) => v.status !== 'pass')) {
              console.warn(`      ⚠  ${r.message}`)
            }
          }
        } catch (err) {
          console.warn(`   ⚠  sitemap.xml generation failed: ${String(err)}`)
        }
      }
    }
  }

  // ── agents.txt + agents.json ───────────────────────────────────────────────
  if (!options.skipAgents) {
    const agentsTxt = generateAgentsTxt(config)
    const agentsTxtPath = join(outDir, 'agents.txt')
    writeFileSync(agentsTxtPath, agentsTxt, 'utf-8')
    console.log(`   ✔  agents.txt  → ${agentsTxtPath}`)
    for (const r of validateAgentsTxt(agentsTxt).filter((v) => v.status !== 'pass')) {
      console.warn(`      ⚠  ${r.message}`)
    }

    const agentsJson = generateAgentsJson(config)
    const agentsJsonPath = join(outDir, 'agents.json')
    writeFileSync(agentsJsonPath, agentsJson, 'utf-8')
    console.log(`   ✔  agents.json → ${agentsJsonPath}`)
    for (const r of validateAgentsJson(agentsJson).filter((v) => v.status !== 'pass')) {
      console.warn(`      ⚠  ${r.message}`)
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log('\n✅ Done!\n')
  const baseUrl = config.site.url.replace(/\/$/, '')
  console.log(`   Site:       ${config.site.url}`)
  if (!options.skipLlms) console.log(`   llms.txt:    ${baseUrl}/llms.txt`)
  const driverType = config.content?.driver?.type
  const sitemapEmitted =
    !options.skipSitemap &&
    (options.sitemap || driverType === 'static' || driverType === 'manual') &&
    !(driverType === 'sitemap' && options.sitemap)
  if (sitemapEmitted) console.log(`   sitemap.xml: ${baseUrl}/sitemap.xml`)
  if (!options.skipAgents) {
    console.log(`   agents.txt:  ${baseUrl}/agents.txt`)
    console.log(`   agents.json: ${baseUrl}/agents.json`)
  }

  if (config.payments?.enabled) {
    const protocols = config.payments.protocols ?? []
    console.log(`   💰 Payments: ${protocols.join(', ')}`)
  } else {
    console.log(`   💡 Payments disabled. Add payments config to monetize agent access.`)
  }
  console.log()
}
