// ─────────────────────────────────────────────────────────────────────────────
// Headers — generators for the §4.5 deployment-side response headers.
//
// agents.txt spec §4.5 mandates four response headers on /agents.txt and
// /agents.json: a Content-Type with charset (for agents.txt), an
// Access-Control-Allow-Origin: *, and a SHOULD-set Cache-Control. Static-asset
// pipelines on most hosting platforms do not set these by default, so adopters
// need to wire the headers in some platform-specific way.
//
// This module emits the right config file for the platform the adopter is
// deploying to. The CLI calls `generateHeadersFile(platform)` and writes the
// result to disk. See `headersDeploymentNote()` for the per-platform guidance
// the CLI can print after writing.
// ─────────────────────────────────────────────────────────────────────────────

export type HostingPlatform = 'cloudflare' | 'netlify' | 'vercel' | 'unknown'

export interface HeadersFile {
  /** Filename relative to the project root (or `--out` directory for `_headers`-style files). */
  filename: string
  /** Whether the path is relative to `--out` (the public/static directory) or the project root. */
  pathRelativeTo: 'out' | 'project-root'
  /** File contents (full file, ready to write). */
  content: string
  /**
   * How the CLI should treat an existing file at the same path:
   *   - `overwrite`  : replace unconditionally (safe for `_headers`, which we own)
   *   - `merge-json` : parse existing JSON, merge our headers entries, write back
   */
  strategy: 'overwrite' | 'merge-json'
}

const HEADERS_FILE_BODY = `# agents.txt spec §4.5 — Serving Requirements
# https://agentstxt.dev  (§4.5)
# Generated by agentify. Safe to hand-edit; \`agentify generate\` regenerates.

/agents.txt
  Content-Type: text/plain; charset=utf-8
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=3600

/agents.json
  Content-Type: application/json
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=3600
`

export interface VercelHeaderEntry {
  source: string
  headers: Array<{ key: string; value: string }>
}

const VERCEL_HEADER_ENTRIES: VercelHeaderEntry[] = [
  {
    source: '/agents.txt',
    headers: [
      { key: 'Content-Type', value: 'text/plain; charset=utf-8' },
      { key: 'Access-Control-Allow-Origin', value: '*' },
      { key: 'Cache-Control', value: 'public, max-age=3600' },
    ],
  },
  {
    source: '/agents.json',
    headers: [
      { key: 'Content-Type', value: 'application/json' },
      { key: 'Access-Control-Allow-Origin', value: '*' },
      { key: 'Cache-Control', value: 'public, max-age=3600' },
    ],
  },
]

/**
 * Build the §4.5 headers config file for the given platform.
 *
 * Output layout per platform:
 *   - cloudflare / netlify : `_headers` written into `--out` (the public dir)
 *   - vercel               : `vercel.json` written to the project root, merged
 *                            with any existing config (CLI handles the read+merge)
 *   - unknown              : `_headers` written into `--out` (best-effort default,
 *                            CLI prints a warning that the user must wire it up
 *                            on their host)
 */
export function generateHeadersFile(platform: HostingPlatform): HeadersFile {
  switch (platform) {
    case 'cloudflare':
    case 'netlify':
    case 'unknown':
      return {
        filename: '_headers',
        pathRelativeTo: 'out',
        content: HEADERS_FILE_BODY,
        strategy: 'overwrite',
      }
    case 'vercel':
      return {
        filename: 'vercel.json',
        pathRelativeTo: 'project-root',
        content: JSON.stringify({ headers: VERCEL_HEADER_ENTRIES }, null, 2) + '\n',
        strategy: 'merge-json',
      }
  }
}

/** Returns the §4.5 entries that must be present in `vercel.json#headers`. */
export function vercelHeaderEntries(): VercelHeaderEntry[] {
  return VERCEL_HEADER_ENTRIES.map((e) => ({ source: e.source, headers: e.headers.map((h) => ({ ...h })) }))
}

/**
 * Merge our §4.5 entries into an existing vercel.json `headers` array. Any
 * existing entries with a different `source` are preserved verbatim. Entries
 * with a colliding `source` (`/agents.txt`, `/agents.json`) are replaced so
 * the §4.5 values win — this is intentional: we own those two paths, the user
 * configures the rest. Returns the merged array.
 */
export function mergeVercelHeaders(existing: unknown): VercelHeaderEntry[] {
  const ours = vercelHeaderEntries()
  const ourSources = new Set(ours.map((e) => e.source))
  const preserved = Array.isArray(existing)
    ? (existing as VercelHeaderEntry[]).filter(
        (e) => e && typeof e === 'object' && typeof e.source === 'string' && !ourSources.has(e.source),
      )
    : []
  return [...preserved, ...ours]
}

/** A short, human-readable explanation of where the file was written and why. */
export function headersDeploymentNote(platform: HostingPlatform): string {
  switch (platform) {
    case 'cloudflare':
      return 'Cloudflare Workers / Pages: `_headers` is read at deploy time from the assets root. No further wiring needed.'
    case 'netlify':
      return 'Netlify: `_headers` is read at deploy time from the publish root. No further wiring needed.'
    case 'vercel':
      return 'Vercel: `vercel.json#headers` is applied at the edge. Existing entries are preserved; only `/agents.txt` and `/agents.json` were touched.'
    case 'unknown':
      return (
        'Hosting platform not detected. Emitted `_headers` (Cloudflare / Netlify syntax) as a best-effort default. ' +
        'If you deploy elsewhere (nginx, Apache, Caddy, S3+CloudFront, etc.), translate the rules into your platform\'s mechanism. ' +
        'See README §4.5 deployment table.'
      )
  }
}
